export enum AUTH_CODE_USAGE {
  NOT_SET = 'NOT_SET',
  SIGN_UP_VERIFY = 'SIGN_UP_VERIFY',
  PHONE_VERIFY = 'PHONE_VERIFY',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
}
